name: build-and-upload-artifacts-to-s3
on:
  release:
    types: [published]
jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: X64
            build_cmd: --pure -A all
            s3_path: amd64
          - arch: ARM64
            build_cmd: -A all --arg pkgs '(import ./nixpkgs.nix { }).pkgsCross.aarch64-multiplatform'
            s3_path: aarch64
    name: Build ${{ matrix.arch }} artifacts
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository at release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      
      - name: Setup Nix environment
        uses: cachix/install-nix-action@v30
      
      - name: Build architecture-specific artifacts
        run: nix-build ${{ matrix.build_cmd }}
      
      - name: Upload build artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.arch }}
          path: ./result/*

  upload-to-s3:
    needs: build
    strategy:
      matrix:
        include:
          - arch: X64
            s3_path: amd64
            top_lvl_folder: x86_64
          - arch: ARM64
            s3_path: aarch64
            top_lvl_folder: aarch64
    name: Upload ${{ matrix.arch }} to S3
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download build artifacts from GitHub
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Sync artifacts to S3
        run: aws s3 sync artifacts/build-${{ matrix.arch }}/${{matrix.top_lvl_folder}} s3://${{ secrets.AWS_S3_BUCKET }}/${{ matrix.s3_path }}/enclave-blobs-default/
